forum_modules/exporter/urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
from django.utils.translation import ugettext as _

from views import state, running, download

urlpatterns = patterns('',
    url(r'^%s%s%s$' % (_('admin/'), _('exporter/'), _('state/')),  state, name='exporter_state'),
    url(r'^%s(?P<mode>\w+)/%s$' % (_('admin/'), _('running/')),  running, name='exporter_running'),
    url(r'^%s%s%s$' % (_('admin/'), _('exporter/'), _('download/')),  download, name='exporter_download'),
)

forum_modules/robotstxt/urls.py
from django.conf.urls.defaults import *
from django.http import  HttpResponse
import settings

urlpatterns = patterns('',
    (r'^robots.txt$',  lambda r: HttpResponse(settings.ROBOTS_FILE.value)),
)

forum_modules/updates/urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
from django.utils.translation import ugettext as _

from views import updater_index, updater_check

urlpatterns = patterns('',
    url(r'^%s%s%s$' % (_('admin/'), _('updater/'), _('check/')),  updater_check, name='updater_check'),
)

urls.py
from django.conf.urls.defaults import *
from django.utils.translation import ugettext as _
from django.conf import settings

urlpatterns = patterns('',
    (r'', include('forum.urls')),
)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns = patterns('',
        url(r'^rosetta/', include('rosetta.urls')),
    ) + urlpatterns

handler404 = 'forum.views.meta.page'
handler500 = 'forum.views.meta.error_handler'

forum/models/meta.py
from django.utils.translation import ugettext as _
from base import *

class Vote(models.Model):
    user = models.ForeignKey(User, related_name="votes")
    node = models.ForeignKey(Node, related_name="votes")
    value = models.SmallIntegerField()
    action = models.OneToOneField(Action, related_name="vote")
    voted_at = models.DateTimeField(default=datetime.datetime.now)

    class Meta:
        app_label = 'forum'
        unique_together = ('user', 'node')


class Flag(models.Model):
    user = models.ForeignKey(User, related_name="flags")
    node = models.ForeignKey(Node, related_name="flags")
    reason = models.CharField(max_length=300)
    action = models.OneToOneField(Action, related_name="flag")
    flagged_at = models.DateTimeField(default=datetime.datetime.now)

    class Meta:
        app_label = 'forum'
        unique_together = ('user', 'node')


class Badge(BaseModel):
    GOLD = 1
    SILVER = 2
    BRONZE = 3

    type        = models.SmallIntegerField()
    cls         = models.CharField(max_length=50, null=True)
    awarded_count = models.PositiveIntegerField(default=0)
    
    awarded_to    = models.ManyToManyField(User, through='Award', related_name='badges')

    def get_handler(self):
        from forum.badges import BadgesMeta
        return BadgesMeta.by_id.get(self.id, None)

    @property
    def name(self):
        cls = self.get_handler()
        return cls and cls.name or _("Unknown")

    @property
    def description(self):
        cls = self.get_handler()
        return cls and cls.description or _("No description available")

    @models.permalink
    def get_absolute_url(self):
        return ('badge', [], {'id': self.id, 'slug': slugify(self.name)})

    def save(self, *args, **kwargs):
        if isinstance(self.awarded_count, models.expressions.ExpressionNode):
            super(Badge, self).save(*args, **kwargs)
            self.awarded_count = self.__class__.objects.filter(id=self.id).values_list('awarded_count', flat=True)[0]
        else:
            super(Badge, self).save(*args, **kwargs)


    class Meta:
        app_label = 'forum'


class Award(models.Model):
    user = models.ForeignKey(User)
    badge = models.ForeignKey('Badge', related_name="awards")
    node = models.ForeignKey(Node, null=True)

    awarded_at = models.DateTimeField(default=datetime.datetime.now)

    trigger = models.ForeignKey(Action, related_name="awards", null=True)
    action = models.OneToOneField(Action, related_name="award")


    class Meta:
        unique_together = ('user', 'badge', 'node')
        app_label = 'forum'

forum/models/question.py
from base import *
from tag import Tag
from django.utils.translation import ugettext as _

class QuestionManager(NodeManager):
    def search(self, keywords, **kwargs):
        return False, self.filter(models.Q(title__icontains=keywords) | models.Q(body__icontains=keywords))

class Question(Node):
    class Meta(Node.Meta):
        proxy = True

    answer_count = DenormalizedField("children", ~models.Q(state_string__contains="(deleted)"), node_type="answer")
    accepted_count = DenormalizedField("children", ~models.Q(state_string__contains="(deleted)"), node_type="answer", marked=True)
    favorite_count = DenormalizedField("actions", action_type="favorite", canceled=False)

    friendly_name = _("question")
    objects = QuestionManager()

    @property
    def closed(self):
        return self.nis.closed

    @property    
    def view_count(self):
        return self.extra_count

    @property
    def headline(self):
        return self._headline()

    def _headline(self):
        if self.nis.deleted:
            return _('[deleted] ') + self.title

        if self.nis.closed:
            return _('[closed] ') + self.title

        return self.title

    @property
    def accepted_answers(self):
        return self.answers.filter(~models.Q(state_string__contains="(deleted)"), marked=True)

    @models.permalink    
    def get_absolute_url(self):
        return ('question', (), {'id': self.id, 'slug': django_urlquote(slugify(self.title))})
        
    def meta_description(self):
        return self.summary

    def get_revision_url(self):
        return reverse('question_revisions', args=[self.id])

    def get_related_questions(self, count=10):
        cache_key = '%s.related_questions:%d:%d' % (settings.APP_URL, count, self.id)
        related_list = cache.get(cache_key)

        if related_list is None:
            related_list = Question.objects.filter_state(deleted=False).values('id').filter(tags__id__in=[t.id for t in self.tags.all()]
            ).exclude(id=self.id).annotate(frequency=models.Count('id')).order_by('-frequency')[:count]
            cache.set(cache_key, related_list, 60 * 60)

        return [Question.objects.get(id=r['id']) for r in related_list]
    



class QuestionSubscription(models.Model):
    user = models.ForeignKey(User)
    question = models.ForeignKey(Node)
    auto_subscription = models.BooleanField(default=True)
    last_view = models.DateTimeField(default=datetime.datetime.now())

    class Meta:
        app_label = 'forum'


class QuestionRevision(NodeRevision):
    class Meta:
        proxy = True
        

forum/views/users.py
from forum.models import User
from django.db.models import Q, Count
from django.core.paginator import Paginator, EmptyPage, InvalidPage
from django.template.defaultfilters import slugify
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from django.http import HttpResponse, HttpResponseRedirect, Http404
from forum.http_responses import HttpResponseUnauthorized
from django.utils.translation import ugettext as _
from django.utils.http import urlquote_plus
from django.utils.html import strip_tags
from django.utils.encoding import smart_unicode
from django.utils import simplejson
from django.core.urlresolvers import reverse, NoReverseMatch
from forum.forms import *
from forum.utils.html import sanitize_html
from forum.modules import decorate, ReturnImediatelyException
from datetime import datetime, date
from forum.actions import EditProfileAction, FavoriteAction, BonusRepAction, SuspendAction
from forum.modules import ui
from forum.utils import pagination
from forum.views.readers import QuestionListPaginatorContext, AnswerPaginatorContext
from forum.settings import ONLINE_USERS
 
import time
import datetime
import decorators

class UserReputationSort(pagination.SimpleSort):
    def apply(self, objects):
        return objects.order_by('-is_active', self.order_by)

class UserListPaginatorContext(pagination.PaginatorContext):
    def __init__(self, pagesizes=(20, 35, 60), default_pagesize=35):
        super (UserListPaginatorContext, self).__init__('USERS_LIST', sort_methods=(
            (_('reputation'), UserReputationSort(_('reputation'), '-reputation', _("sorted by reputation"))),
            (_('newest'), pagination.SimpleSort(_('recent'), '-date_joined', _("newest members"))),
            (_('last'), pagination.SimpleSort(_('oldest'), 'date_joined', _("oldest members"))),
            (_('name'), pagination.SimpleSort(_('by username'), 'username', _("sorted by username"))),
        ), pagesizes=pagesizes, default_pagesize=default_pagesize)

class SubscriptionListPaginatorContext(pagination.PaginatorContext):
    def __init__(self):
        super (SubscriptionListPaginatorContext, self).__init__('SUBSCRIPTION_LIST', pagesizes=(5, 10, 20), default_pagesize=20)

class UserAnswersPaginatorContext(pagination.PaginatorContext):
    def __init__(self):
        super (UserAnswersPaginatorContext, self).__init__('USER_ANSWER_LIST', sort_methods=(
            (_('oldest'), pagination.SimpleSort(_('oldest answers'), 'added_at', _("oldest answers will be shown first"))),
            (_('newest'), pagination.SimpleSort(_('newest answers'), '-added_at', _("newest answers will be shown first"))),
            (_('votes'), pagination.SimpleSort(_('popular answers'), '-score', _("most voted answers will be shown first"))),
        ), default_sort=_('votes'), pagesizes=(5, 10, 20), default_pagesize=20, prefix=_('answers'))

USERS_PAGE_SIZE = 35# refactor - move to some constants file

@decorators.render('users/users.html', 'users', _('users'), weight=200)
def users(request):
    suser = request.REQUEST.get('q', "")
    users = User.objects.all()

    if suser != "":
        users = users.filter(username__icontains=suser)

    return pagination.paginated(request, ('users', UserListPaginatorContext()), {
        "users" : users,
        "suser" : suser,
    })


@decorators.render('users/online_users.html', 'online_users', _('Online Users'), weight=200, tabbed=False)
def online_users(request):
    suser = request.REQUEST.get('q', "")

    sort = ""
    if request.GET.get("sort", None):
        try:
            sort = int(request.GET["sort"])
        except ValueError:
            logging.error('Found invalid sort "%s", loading %s, refered by %s' % (
                request.GET.get("sort", ''), request.path, request.META.get('HTTP_REFERER', 'UNKNOWN')
            ))
            raise Http404()

    page = 0
    if request.GET.get("page", None):
        try:
            page = int(request.GET["page"])
        except ValueError:
            logging.error('Found invalid page "%s", loading %s, refered by %s' % (
                request.GET.get("page", ''), request.path, request.META.get('HTTP_REFERER', 'UNKNOWN')
            ))
            raise Http404()

    pagesize = 10
    if request.GET.get("pagesize", None):
        try:
            pagesize = int(request.GET["pagesize"])
        except ValueError:
            logging.error('Found invalid pagesize "%s", loading %s, refered by %s' % (
                request.GET.get("pagesize", ''), request.path, request.META.get('HTTP_REFERER', 'UNKNOWN')
            ))
            raise Http404()


    users = None
    if sort == "reputation":
        users = sorted(ONLINE_USERS.sets.keys(), key=lambda user: user.reputation)
    elif sort == "newest" :
        users = sorted(ONLINE_USERS.sets.keys(), key=lambda user: user.newest)
    elif sort == "last":
        users = sorted(ONLINE_USERS.sets.keys(), key=lambda user: user.last)
    elif sort == "name":
        users = sorted(ONLINE_USERS.sets.keys(), key=lambda user: user.name)
    elif sort == "oldest":
        users = sorted(ONLINE_USERS.sets.keys(), key=lambda user: user.oldest)
    elif sort == "newest":
        users = sorted(ONLINE_USERS.sets.keys(), key=lambda user: user.newest)
    elif sort == "votes":
        users = sorted(ONLINE_USERS.sets.keys(), key=lambda user: user.votes)
    else:
        users = sorted(ONLINE_USERS.iteritems(), key=lambda x: x[1])

    return render_to_response('users/online_users.html', {
        "users" : users,
        "suser" : suser,
        "sort" : sort,
        "page" : page,
        "pageSize" : pagesize,
    })


def edit_user(request, id, slug):
    user = get_object_or_404(User, id=id)
    if not (request.user.is_superuser or request.user == user):
        return HttpResponseUnauthorized(request)
    if request.method == "POST":
        form = EditUserForm(user, request.POST)
        if form.is_valid():
            new_email = sanitize_html(form.cleaned_data['email'])

            if new_email != user.email:
                user.email = new_email
                user.email_isvalid = False

                try:
                    hash = ValidationHash.objects.get(user=request.user, type='email')
                    hash.delete()
                except:
                    pass

            if settings.EDITABLE_SCREEN_NAME:
                user.username = sanitize_html(form.cleaned_data['username'])
            user.real_name = sanitize_html(form.cleaned_data['realname'])
            user.website = sanitize_html(form.cleaned_data['website'])
            user.location = sanitize_html(form.cleaned_data['city'])
            user.date_of_birth = form.cleaned_data['birthday']
            if user.date_of_birth == "None":
                user.date_of_birth = datetime(1900, 1, 1, 0, 0)
            user.about = sanitize_html(form.cleaned_data['about'])

            user.save()
            EditProfileAction(user=user, ip=request.META['REMOTE_ADDR']).save()

            request.user.message_set.create(message=_("Profile updated."))
            return HttpResponseRedirect(user.get_profile_url())
    else:
        form = EditUserForm(user)
    return render_to_response('users/edit.html', {
    'user': user,
    'form' : form,
    'gravatar_faq_url' : reverse('faq') + '#gravatar',
    }, context_instance=RequestContext(request))


@decorate.withfn(decorators.command)
def user_powers(request, id, action, status):
    if not request.user.is_superuser:
        raise decorators.CommandException(_("Only superusers are allowed to alter other users permissions."))

    if (action == 'remove' and 'status' == 'super') and not request.user.is_siteowner():
        raise decorators.CommandException(_("Only the site owner can remove the super user status from other user."))

    user = get_object_or_404(User, id=id)
    new_state = action == 'grant'

    if status == 'super':
        user.is_superuser = new_state
    elif status == 'staff':
        user.is_staff = new_state
    else:
        raise Http404()

    user.save()
    return decorators.RefreshPageCommand()


@decorate.withfn(decorators.command)
def award_points(request, id):
    if not request.POST:
        return render_to_response('users/karma_bonus.html')

    if not request.user.is_superuser:
        raise decorators.CommandException(_("Only superusers are allowed to award reputation points"))

    try:
        points = int(request.POST['points'])
    except:
        raise decorators.CommandException(_("Invalid number of points to award."))

    user = get_object_or_404(User, id=id)

    extra = dict(message=request.POST.get('message', ''), awarding_user=request.user.id, value=points)

    BonusRepAction(user=request.user, extra=extra).save(data=dict(value=points, affected=user))

    return {'commands': {
            'update_profile_karma': [user.reputation]
        }}
    

@decorate.withfn(decorators.command)
def suspend(request, id):
    user = get_object_or_404(User, id=id)

    if not request.user.is_superuser:
        raise decorators.CommandException(_("Only superusers can suspend other users"))

    if not request.POST.get('bantype', None):
        if user.is_suspended():
            suspension = user.suspension
            suspension.cancel(user=request.user, ip=request.META['REMOTE_ADDR'])
            return decorators.RefreshPageCommand()
        else:
            return render_to_response('users/suspend_user.html')

    data = {
        'bantype': request.POST.get('bantype', 'Indefinitely').strip(),

forum/skins/default/templates/503.html
{% load i18n %}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>{% trans "System down for maintenance" %}</title>
        <style>
            #content {
                margin: auto;
            }
        </style>
    </head>
    <body>
        <div id="content">
            <img src="{{ app_logo }}">
            <p>{{ app_title }}</p>
            <h3>{% trans "System down for maintenance" %}</h3>
            <br/>
            {{ message }}
        </div>
    </body>
</html>

forum/skins/default/templates/account_settings.html
{% extends "base_content.html" %}
<!-- settings.html -->
{% load i18n %}
{% block title %}{% spaceless %}{% trans "Account functions" %}{% endspaceless %}{% endblock %}
{% block head %}
<style type="text/css" media="screen">
    h4 {font-size:12pt;}
	dt, dd { padding:0 0 0.35em 0; }
	dt { float: left; width: 21ex;  }
	dd { margin-left: 23ex;  }
	
	#settings-options, #settings-intro { padding: 4em 1.5em;}
	#settings-options { min-height: 300px; border-left: 1px solid #333;}
	
	#settings-options h5 { font-weight: bold;}
</style>
{% endblock %}

{% block content %}
<div id="main-bar">
    <h3><strong>{{ request.user.username }} {% trans "Profile" %}</strong></h3>
</div>
<div id="settings-options">
	{% if msg %}
		<p class="error">{{ msg }}</p>
	{% endif %}

	<dl class="list-item">
        <dt>&raquo; <a href="{% url user_changepw %}">{% trans "Change password" %}</a></dt>
        <dd>{% trans "Give your  account a new password." %}</dd>
        {% comment %}
        <dt>&raquo; <a href="{% url user_changeemail %}">{% trans "Change email " %}</a></dt>
        <dd>{% trans "Add or update the email address associated with your account." %}</dd>

        <dt>&raquo; <a href="{% url user_changeopenid %}">{% trans "Change OpenID" %}</a></dt>
        <dd>{% trans "Change openid associated to your account" %}</dd>

        
        <dt>&raquo; <a href="{% url user_delete %}">{% trans "Delete account" %}</a></dt>
        <dd>{% trans "Erase your username and all your data from website" %}</dd>
        {% endcomment %}
	</dl>
</div>
{% endblock %}
<!-- end settings.html -->

forum/skins/default/templates/badge.html
{% extends "base_content.html" %}
<!-- template badge.html -->
{% load i18n %}
{% load extra_tags %}
{% load user_tags %}
{% load humanize %}
{% block title %}{% spaceless %}{{ badge.name }} - {% trans "Badge" %}{% endspaceless %}{% endblock %}
{% block forejs %}
       <script type="text/javascript">
        $().ready(function(){
            $("#nav_badges").attr('className',"on");
        });
         
        </script>
{% endblock %}
{% block content %}
<div id="main-bar" class="headNormal">
	{% trans "Badge" %}
</div>
<div id="main-body" style="width:100%;margin-bottom:20px">
    <p>
        <a href="{{badge.get_absolute_url}}" title="{{ badge.get_type_display }} : {{ badge.description }}" class="medal"><span class="badge{{ badge.type }}">&#9679;</span>&nbsp;{{ badge.name }}</a> {{ badge.description }}
    </p>
    <div>
        {% if badge.awarded_count %}
        <p style="float:left"><span class="count">{{ award_count|intcomma }}</span>
        <strong>{% trans "The users have been awarded with badges:" %}</strong></p>
        {% endif %}
    </div>
    <div id="award-list" style="clear:both;margin-left:20px;line-height:25px;">
        {% for award in awards %}
        <p style="width:220px;float:left">{% user_signature award.user "badges" %}<span class="tag-number"> &#215; {{ award.count|intcomma }}</span></p>
        {% endfor %}
    </div>

</div>
{% endblock %}
<!-- end template badge.html -->

forum/skins/default/templates/base.html
{% extends "base_content.html" %}
{% block page_center %}

{% block full_width_banner %}{% endblock %}

<div id="wrapper">
    {% block site_width_banner %}{% endblock %}
    
    <div id="room">
        <div id="CALeft">
            {% block content%}
            {% endblock%}

        </div>
        <div id="CARight">
            {% block sidebar%}
            {% endblock%}

        </div>
        <div id="tail" style="clear:both;">
            {% block tail %}
            {% endblock %}
        </div>
    </div>
    <div class="spacer3"></div>
</div>
{% endblock %}

forum/skins/default/templates/close.html
{% extends "base_content.html" %}
<!-- template close.html -->
{% load i18n %}
{% load extra_tags %}
{% load humanize %}
{% block title %}{% spaceless %}{% trans "Close question" %}{% endspaceless %}{% endblock %}
{% block forejs %}
       <script type="text/javascript">
        $().ready(function(){
            $('#btBack').bind('click', function(){ history.back(); });
        });
        </script>
{% endblock %}
{% block content %}
<div id="main-bar" class="headNormal">
	{% trans "Close question" %}
</div>
<div id="main-body" style="width:100%;margin-bottom:10px">
    <p>{% trans "Close the question" %}: <a href="{{ question.get_absolute_url }}">
    <strong>{{ question.get_question_title }}</strong></a>
    </p>   
    
    <form id="fmclose" action="{% url close question.id %}" method="post" >
        {% csrf_token %}
        <p>
            <strong>{% trans "Reasons" %}:</strong> {{ form.reason }}
        </p>
        <div id="" style="padding-top:20px">
            <input type="submit" value="{% trans "OK to close" %}" class="submit" />
            <input id="btBack" type="button" class="submit" value="{% trans "Cancel" %}"  />
            
        </div>
        
    </form>
</div>
{% endblock %}
<!-- end template close.html -->

forum/skins/default/templates/email_base.html
{% load extra_filters %}
{% load extra_tags %}
{% load email_tags %}
{% load i18n %}

<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <style type="text/css">
            body {
                background: #FFF;
                font-size: 12px;
                line-height: 150%;
                margin: 0;
                padding: 0;
                color: #000;
                font-family: sans-serif;
            }

            #wrapper {
                width: 600px;
                margin: auto;
                padding: 0;
            }

            a img {
                border: none;
            }
        </style>
    </head>
    <body>
        <a href="{% fullurl index %}">
            <img src="cid:logo" title="{% trans "home" %}" alt="{{settings.APP_TITLE}} logo"/>
        </a>
        <br />
        <p>{{ settings.APP_TITLE }}</p>
    <br /><br />
    <div id="wrapper">
            <div id="room">
                <div id="CALeft">
                    {% block content%}
                    {% endblock%}
                </div>
            </div>
            <div class="spacer3"></div>
        </div>
    </body>
</html>

forum/skins/default/templates/header.html
<!-- template header.html -->
{% load extra_tags ui_registry i18n extra_filters markup %}

	<div id="roof">
	  
		<div id="logo">
			<a href="{% url index %}">
				<img src="{{ settings.APP_LOGO }}" title="{% trans "back to home page" %}" alt="{{settings.APP_TITLE}} logo"/>
			</a>
		</div>
	  
		<div id="top">
		    {% loadregistry header_links %}{% endloadregistry %}
		</div>

    <div id="nav">
        {% loopregistry page_top_tabs %}{% spaceless %}
            <a id="nav_{{ tab_name }}"{% ifequal tab tab_name %} class="on"{% endifequal %} href="{{ tab_url }}" >{{ tab_title }}</a>
        {% endspaceless %}{% endloopregistry %}
        <a id="nav_ask" href="{% url ask %}" class="special">{% trans "ask a question" %}</a>
    </div>
  </div>

  <div class="clear"></div>
  
	<div id="searchBar">
    <form action="{% url search %}" method="get">
        {% csrf_token %}
        <div>
            <input type="text" class="searchInput" value="{{ keywords }}" name="q" id="keywords" />
            <input type="submit" name="Submit" value="{% trans "search" %}" class="searchBtn" />
        </div>
        <div class="options">
            <input id="type-question" type="radio" value="question" name="t" 
                checked="checked" /><label for="type-question">{% trans "questions" %}</label>
            <input id="type-tag" type="radio" value="tag" name="t" /><label for="type-tag">{% trans "tags" %}</label>
            <input id="type-user" type="radio" value="user" name="t" /><label for="type-user">{% trans "users" %}</label>
        </div>
    </form>	
	</div>

	{% if settings.USE_ANNOUNCEMENT_BAR|or_preview:request %}
  <div id="announcement">
      {{ settings.ANNOUNCEMENT_BAR|or_preview:request|static_content:settings.ANNOUNCEMENT_BAR_RENDER_MODE }}
  </div>
  {% endif %}

<!-- end template header.html -->

forum/skins/default/templates/notarobot.html
{% extends "base_content.html" %}
{% load i18n %}
{% block title %}{% spaceless %}{% trans "Please prove that you are a Human Being" %}{% endspaceless %}{% endblock %}
{% block content %}
{% comment %} this form is set up to be used in wizards {% endcomment %}
<form name="notarobot" action="." method="POST">
    {% csrf_token %}
    <div>
    {{form}}
    </div>
    <input type="submit" value="{% trans "I am a Human Being" %}" class="submit" style="float:left"/>
    <input type="hidden" name="{{ step_field }}" value="{{ step0 }}" />
    {{ previous_fields|safe }}
    </form>
</form>
{% endblock %}

forum/skins/default/templates/page.html
{% extends base %}
{% load i18n markup node_tags general_sidebar_tags %}
{% block title %}{% spaceless %}{{ page.title }}{% endspaceless %}{% endblock %}

{% block content %}
<div class="headNormal">{{ page.title }}</div>
<div class="content">
{{ body }}
</div>
{% if page.extra.comments %}
    {% comments page request.user %}
{% endif %}
{% endblock %}

{% ifequal page.extra.template "sidebar" %}
    {% block sidebar %}
        {% sidebar_upper %}
        {% if page.extra.sidebar %}
            {% if page.extra.sidebar_wrap %}<div class="boxC"><div class="body">{% endif %}
                {{ sidebar }}
            {% if page.extra.sidebar_wrap %}</div></div>{% endif %}
        {% endif %}
        {% sidebar_lower %}
    {% endblock %}
{% endifequal %}

forum/skins/default/templates/reopen.html
{% extends "base_content.html" %}
<!-- reopen.html -->
{% load extra_tags %}
{% load i18n %}
{% load humanize %}
{% block title %}{% spaceless %}{% trans "Reopen question" %}{% endspaceless %}{% endblock %}
{% block forejs %}
       <script type="text/javascript">
        $().ready(function(){
            $('#btBack').bind('click', function(){ history.back(); });
        });
        </script>
{% endblock %}
{% block content %}
<div id="main-bar" class="headNormal">
	{% trans "Reopen question" %}
</div>
<div id="main-body" style="width:100%">
    <p>{% trans "Open the previously closed question" %}: <a href="{{ question.get_absolute_url }}"><span class="big">{{ question.headline }}</span></a>
    
    </p>   
    <p><strong>{% trans "The question was closed for the following reason " %}"{{ question.get_close_reason_display }}"{% trans "reason - leave blank in english" %} <a href="{{ question.closed_by.get_profile_url }}">{{ question.closed_by.username }}</a> {% trans "on "%} {% diff_date question.closed_at %}<font class="darkred">{% trans "date closed" %}</font>
        </strong>
    </p>
    
    <form id="fmclose" action="{% url reopen question.id %}" method="post">
        {% csrf_token %}
        <div id="" style="padding:20px 0 20px 0">
            <input type="submit" value="{% trans "Reopen this question" %}" class="submit" />
            <input id="btBack" type="button" value="{% trans "Cancel" %}"  class="submit"  />
        </div>
    </form>
</div>
{% endblock %}
<!-- end reopen.html -->